# Project Information
site_name: 白阁文库
site_description: 白阁文库
site_author: BaizeSec Team
site_url: https://baizesec.github.io/bylibrary/

# Repository
repo_name: 'BaizeSec/bylibrary'
repo_url: 'https://github.com/BaizeSec/bylibrary'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 - 2020 BaizeSec Team'

site_dir: ./../html

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
    scheme: preference
  
  icon:
    logo: 'material/school'
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'
# Contents
